module.exports = {
  WRONG_ARGUMENT_COUNT: 1,
  INVALID_COMMAND: 2,
  INVALID_ENVIRONMENT: 3,
  DIRECTORY_IS_A_FILE: 4,
  DIRECTORY_CREATE_FAILED: 5,
  SET_ALREDY_EXISTS: 6,
  SET_NOT_FOUND: 7,
  NOT_ROOT: 8
};